BaseURL = "https://dvesti.github.io/prorab/"
Title = "Alien's Notes"
theme = ["refined"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

ignoreErrors = ["error-remote-getjson"]

# Remove files from destination not found in static directories
cleandestinationdir = true

# https://gohugo.io/extras/highlighting/

# Syntax highlighting using Pygments
# $ python
# >>> from pygments.styles import STYLE_MAP
# >>> STYLE_MAP.keys()
# ['manni', 'igor', 'lovelace', 'xcode', 'vim', 'autumn', 'vs', 'rrt', 'native',
# 'perldoc', 'borland', 'tango', 'emacs', 'friendly', 'monokai', 'paraiso-dark',
# 'colorful', 'murphy', 'bw', 'pastie', 'algol_nu', 'paraiso-light', 'trac',
# 'default', 'algol', 'fruity']
pygmentsStyle = "native"
#pygmentsStyle = "monokai" #"stata" #emacs" #"trac"        # This is not needed as the theme is set using external CSS -- Tue Sep 26 13:26:59 EDT 2017 - kmodi
pygmentsCodeFences = true       # This applies to Chroma too.
# Use pygmentize generated CSS file instead of inlining the code codes in the HTML.
# See https://gohugo.io/tools/syntax-highlighting/#pygments and
# https://github.com/richleland/pygments-css
pygmentsUseClasses = false #true       # This applies to Chroma too.
pygmentsUseClassic = false      # Needs Hugo 0.28+, default=false => Use Chroma for syntax highlighting
pygmentsOptions = "linenos=table"
# pygmentsCodefencesGuessSyntax = true

enableEmoji = true

# Services
# GoogleAnalytics = "UA-105225187-1"
# Mon Mar 26 18:18:27 EDT 2018 - kmodi - Stopped using Disqus today!
# DisqusShortname = "ascriptersnotes"

LanguageCode = "en-us" #"ru-ru" # Used in RSS generation

disableFastRender = true        # Hugo 0.30

[Author]
  name = "Dvesti"
  email = "dvesti@hot.ee"
  bio = "Web-prorab"
 # [Author.photo]
 #   url = "images/me--optimized.jpg" # Path relative to baseURL
 #   width = 400
 #   height = 400

[Social]
  github = "dvesti"
  twitter = "Prorab"

[Permalinks]
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # | :year        | the 4-digit year                           |
  # | :month       | the 2-digit month                          |
  # | :monthname   | the name of the month                      |
  # | :day         | the 2-digit day                            |
  # | :weekday     | the 1-digit day of the week (Sunday = 0)   |
  # | :weekdayname | the name of the day of the week            |
  # | :yearday     | the 1- to 3-digit day of the year          |
  # | :section     | the content's section                      |
  # | :sections    | the content's sections hierarchy           |
  # | :title       | the content's title                        |
  # | :slug        | the content's slug (or title, if no slug)  |
  # | :filename    | the content's filename (without extension) |

  # Below, we have:
  #
  #   foo = "bar"
  #
  # where 'foo' is the section name which we want to have the custom
  # permalinks. If foo is 'posts', it will apply to content in "content/posts/"
  # dir. The "bar" portion is how you want the links to look.
  posts = "/:filename/"
  # post = "/:year/:month/:title/"
  notes = "/notes/:filename/"

[Taxonomies] # [indexes] is obsolete since v0.11
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"
  series = "series"
 
# The "ATOM", "JF2Post" and "JF2Feed" are custom output formats defined in the
# "refined" theme.
[outputs]
  home = ["HTML", "RSS", "ATOM", "JF2Feed"] # default = ["HTML", "RSS"]
  section = ["HTML", "RSS", "ATOM", "JF2Feed"] # posts/atom.xml
  taxonomy = ["HTML", "RSS", "ATOM", "JF2Feed"] # tags/foo/atom.xml
  # Fri Mar 23 17:57:08 EDT 2018 - kmodi
  # There's some issue on Hugo 0.38-DEV (older versions too)..  The "ATOM"
  # output format is not getting generated for taxonomyTerm.
  # taxonomyTerm = ["HTML", "RSS", "ATOM", "JF2Feed"]
  taxonomyTerm = ["HTML"] # tags/atom.xml
  page = ["HTML", "JF2Post"]

# https://gohugo.io/getting-started/configuration/#configure-file-caches
[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "1m"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "1m"

[Params]
  # https://gohugo.io/functions/where/#portable-where-filters
  mainSections = ["posts", "notes"]
  tagline = "Заметки вэб-прораба"

  images = ["android-chrome-256x256.png"] # array of image paths relative to <SITE_PROJ>/assets/ dir

  favicons = false #true

  feedSections = ["posts"]

  html5_validator = true

  cache_busting = true
  # cache_busting_debug = true
  # cache_busting_debug = false

 # [Params.source]
 #   url = "https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io"
 #   org_dir = "content-org"
 #   md_dir = "content"
 #   ox_hugo = true

 # [Params.indieweb]
 #   domain = "https://scripter.co/" # must end with a slash
 #   webring = "🏔🐴🎑" # Get your IndieWeb Webring ID from https://xn--sr8hvo.ws
 #   [Params.indieweb.webmention]
 #     endpoint = "https://webmention.io/" # must end with a slash
 #     account = "scripter.co"
    # [Params.indieweb.micropub]
    #   url = "nanopub/nanopub.php"

  [[Params.social]]
    name = "Github"
    link = "https://github.com/dvesti/"
    relme = true
 # [[Params.social]]
 #   name = "Gitlab"
 #   link = "https://gitlab.com/users/kaushalmodi/projects"
 # [[Params.social]]
 #   name = "Hacker News"
 #  link = "https://news.ycombinator.com/user?id=kaushalmodi"
 #   icon = "hacker-news"
  [[Params.social]]
    name = "Twitter"
    link = "https://twitter.com/Prorab/"
 # [[Params.social]]
 #   name = "Mastodon"
 #   link = "https://mastodon.technology/@kaushalmodi"
 #   relme = true
 # [[Params.social]]
 #   name = "Keybase.io"
 #   link = "https://keybase.io/kaushalmodi"
 #  icon = "keybase"

# See var-naming-rules.md for rules when naming keys (variables) and table names
# in this config!
